name: Build, Test, and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app .

  test:
    name: Run Tests in Build Container
    runs-on: ubuntu-latest
    needs: build  # Test job depends on build job completion
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image again (for testing)
        run: |
          docker build -t my-app .

      - name: Run tests in build container
        run: |
          docker run --rm --name my-app-test-container my-app npm test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test  # Only deploy if tests pass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Run production container
        run: |
          docker run -d -p 80:80 --name my-app-container my-app
